# -*- coding: utf-8 -*-
"""Smart User Data Cleaner (v1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1922JCiyE6xgr0m5Lx5dnr9gWHspZ9B76
"""

raw_data ="  AhMeT  yILMAZ ;  23 ;  1.78 ;  ahmetYILMAZ@GMAIL.Com   "

cleaned = raw_data.strip().split(";")

cleaned

isim = cleaned[0].lower().title().strip()

name = isim

name

yas = int(cleaned[1].strip())

age = yasIsleme = float(age+10)

age

boyAnalizi = float(cleaned[2].strip()) * 100

boy = boyAnalizi

boy

emailTemizleme = cleaned[3].lower().strip()

emailTemizleme

kod = emailTemizleme[0:3]

print(f"Kullanıcı: {name}")
print(f"Yaş (10 yıl sonra): {age}")
print(f"Boy (cm): {boy}")
print(f"Email kullanıcı kodu: {kod}")